### ISSUE TITLE
Dont store key and value token in seperate array. Can you parse without storing it in array.? 

### ISSUE THREAD

**Issue by vijaykilledar** [rishikeshgawade/developement#3]
https://github.com/rishikeshgawade/developement/blob/2eb5d955e88975fc6fed4ed14bfd17676126ef74/c/search_key.c#L39

In this loop you are storing every token in key_value[] pointer.
Can we do this without storing it in array.

**Comment by rishikeshgawade** [comment]
Corrected

**Comment by rishikeshgawade** [comment]
Please see search_key_V1.c
